apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
spec:
  allowUnsafeConfigurations: true
  backup:
    coordinator:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enableClientsLogging: true
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 0.1Gi
          storage: 1Gi
    debug: true
    enabled: true
    image: registry.connect.redhat.com/percona/percona-server-mongodb-operator-containers:1.0.0-backup
    restartOnFailure: true
    storages: null
    tasks: null
  image: registry.connect.redhat.com/percona/percona-server-mongodb-operator-containers:1.0.0-mongod4.0.9
  imagePullPolicy: Always
  mongod:
    net:
      hostPort: 0
      port: 27017
    operationProfiling:
      mode: slowOp
      rateLimit: 100
      slowOpThresholdMs: 100
    security:
      redactClientLogData: false
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        collectionConfig:
          blockCompressor: snappy
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        indexConfig:
          prefixCompression: true
  pause: false
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
  replsets:
  - affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    arbiter:
      enabled: false
    expose:
      enabled: false
    name: rs0
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi
  secrets:
    users: my-cluster-name-secrets
